# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3577a549afed2245ae12dac0ca3d3d704320b31745b332aca315f42ec2afc135a124c7a4942bc680feb3275a0d918806c2602e426f61622beb2aa4ac182fb7f2

test:
  secret_key_base: 5b0a15aa0b06888fcc99179525b6e66b682a5325d7df373cdc2c1ad4d36653e7dfdaa6c5a65245f933644ad7cc6c7d5d23530dc6d9f7066df1ebeadeb79c65d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
